# --- plot style (generated by plotpolish; edit above, not here) ---
import matplotlib as mpl
# Hold on to the values this page set, so the style below does not replace them.
_plotpolish_host_rc = {k: mpl.rcParams[k] for k in ["figure.autolayout", "figure.figsize"] if k in mpl.rcParams}
mpl.style.use("seaborn-v0_8")
mpl.rcParams.update(_plotpolish_host_rc)
del _plotpolish_host_rc
mpl.rcParams.update({
    "lines.markersize": 9,
    "axes.linewidth": 1.5,
    "legend.frameon": True,
})
# --- end plot style ---
