# --- plot style (generated by plotpolish; edit above, not here) ---
import matplotlib as mpl
mpl.rcParams.update({
    "axes.prop_cycle": mpl.cycler(color=["#E69F00", "#56B4E9"], linewidth=[2, 1], linestyle=["-", "--"]),
})
# --- end plot style ---
