# --- plot style (generated by plotpolish; edit above, not here) ---
import matplotlib as mpl
mpl.rcParams.update({
    "lines.linewidth": 2,
    "axes.linewidth": 1.2,
    "legend.loc": "upper right",
})
# --- end plot style ---
