# --- plot style (generated by stylefence; edit above, not here) ---
import matplotlib as mpl
mpl.rcParams.update({
    "figure.figsize": [7, 3.5],
    "lines.linewidth": 2,
    "legend.loc": "upper right",
})
# --- end plot style ---
