# --- plot style (generated by stylefence; edit above, not here) ---
import matplotlib as mpl
mpl.style.use("seaborn-v0_8-whitegrid")
mpl.rcParams.update({
    "font.size": 12,
    "axes.grid": True,
    "axes.spines.top": False,
    "axes.spines.right": False,
})
# --- end plot style ---
