"""Execute the golden fenced blocks and check they do what the sidecar JSON says."""

import json
import math
from pathlib import Path

import matplotlib as mpl
import pytest

from plotpolish import TOOL_NAME, list_styles, rc_to_json

FIXTURES = Path(__file__).parent / "fixtures" / "blocks"
NAMES = sorted(p.stem for p in FIXTURES.glob("*.py"))

START = "# --- plot style (generated by %s; edit above, not here) ---" % TOOL_NAME
END = "# --- end plot style ---"


def load(name):
    return (FIXTURES / (name + ".py")).read_text(), json.loads((FIXTURES / (name + ".json")).read_text())


def same(a, b):
    if isinstance(a, dict) and isinstance(b, dict):
        return set(a) == set(b) and all(same(a[k], b[k]) for k in a)
    if isinstance(a, list) and isinstance(b, list):
        return len(a) == len(b) and all(same(x, y) for x, y in zip(a, b))
    if isinstance(a, bool) or isinstance(b, bool):
        return a is b
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return math.isclose(a, b)
    return a == b


@pytest.mark.parametrize("name", NAMES)
def test_block_is_fenced_and_self_contained(name):
    source, _ = load(name)
    lines = source.splitlines()
    assert lines[0] == START and lines[-1] == END
    assert source.count(START) == 1 and source.count(END) == 1
    assert lines[1] == "import matplotlib as mpl"
    assert lines[2].startswith('mpl.style.use("') or lines[2] == "mpl.rcParams.update({"
    assert 'mpl.style.use("default")' not in source, "the block must never reset host rc values"


@pytest.mark.parametrize("name", NAMES)
def test_block_executes_and_sets_rcparams(name):
    source, expected = load(name)
    mpl.rcParams["figure.autolayout"] = True  # what Trinket sets before every run
    namespace = {}
    exec(compile(source, name + ".py", "exec"), namespace)
    assert set(namespace) - {"__builtins__"} == {"mpl"}, "block must bind only 'mpl'"

    assert mpl.rcParams["figure.autolayout"] is True, "host per-run rc values must survive the block"
    if expected["style"] != "default":
        assert expected["style"] in list_styles()
    for key, value in expected["rc"].items():
        assert key in mpl.rcParams, key
        actual = rc_to_json(key, mpl.rcParams[key])
        assert same(actual, value), (key, actual, value)


def test_everything_fixture_covers_every_curated_key():
    from plotpolish import CURATED_KEYS

    _, expected = load("everything")
    assert set(expected["rc"]) == set(CURATED_KEYS)


def test_style_sheet_values_survive_under_overrides():
    source, _ = load("whitegrid")
    exec(source, {})
    assert mpl.rcParams["axes.grid"] is True
    assert mpl.rcParams["axes.edgecolor"] == ".8"  # from the whitegrid sheet, untouched by the block
