"""Execute the golden fenced blocks and check they do what the sidecar JSON says."""

import json
import math
import warnings
from pathlib import Path

import matplotlib as mpl
import matplotlib.style  # noqa: F401  -- for mpl.style.library
import pytest

from plotpolish import TOOL_NAME, list_styles, rc_to_json

FIXTURES = Path(__file__).parent / "fixtures" / "blocks"
NAMES = sorted(p.stem for p in FIXTURES.glob("*.py"))

START = "# --- plot style (generated by %s; edit above, not here) ---" % TOOL_NAME
END = "# --- end plot style ---"

# The name the block binds while it carries the host's rc keys across
# mpl.style.use, and the comment that explains it. Mirrors HOST_RC_VARIABLE in
# src/constants.ts; test_block_executes_and_sets_rcparams is what keeps the
# binding from outliving the block.
HOST_RC_VAR = "_%s_host_rc" % TOOL_NAME
HOST_RC_COMMENT = "# Hold on to the values this page set, so the style below does not replace them."


def load(name):
    return (FIXTURES / (name + ".py")).read_text(), json.loads((FIXTURES / (name + ".json")).read_text())


def same(a, b):
    if isinstance(a, dict) and isinstance(b, dict):
        return set(a) == set(b) and all(same(a[k], b[k]) for k in a)
    if isinstance(a, list) and isinstance(b, list):
        return len(a) == len(b) and all(same(x, y) for x, y in zip(a, b))
    if isinstance(a, bool) or isinstance(b, bool):
        return a is b
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return math.isclose(a, b)
    return a == b


@pytest.mark.parametrize("name", NAMES)
def test_block_is_fenced_and_self_contained(name):
    source, _ = load(name)
    lines = source.splitlines()
    assert lines[0] == START and lines[-1] == END
    assert source.count(START) == 1 and source.count(END) == 1
    assert lines[1] == "import matplotlib as mpl"
    assert (
        lines[2].startswith('mpl.style.use("')
        or lines[2] == "mpl.rcParams.update({"
        or lines[2] == HOST_RC_COMMENT  # the host-rc save preamble, which only precedes a style line
    ), lines[2]
    assert 'mpl.style.use("default")' not in source, "the block must never reset host rc values"
    assert "mpl.rcdefaults" not in source, "the block must never reset host rc values"


@pytest.mark.parametrize("name", NAMES)
def test_block_executes_and_sets_rcparams(name):
    source, expected = load(name)
    namespace = {}
    exec(compile(source, name + ".py", "exec"), namespace)
    assert set(namespace) - {"__builtins__"} == {"mpl"}, "block must bind only 'mpl'"

    if expected["style"] != "default":
        assert expected["style"] in list_styles()
    for key, value in expected["rc"].items():
        assert key in mpl.rcParams, key
        actual = rc_to_json(key, mpl.rcParams[key])
        assert same(actual, value), (key, actual, value)


def test_everything_fixture_covers_every_curated_key():
    from plotpolish import CURATED_KEYS

    _, expected = load("everything")
    assert set(expected["rc"]) == set(CURATED_KEYS)


def strip_host_rc(source):
    """The same block as it read before host keys were carried across the style."""
    return "\n".join(
        line for line in source.splitlines() if HOST_RC_VAR not in line and line != HOST_RC_COMMENT
    )


def test_host_rc_keys_survive_the_style():
    """A style that sets a key the host owns must not take the host's value with it.

    Trinket's worker sets a pane-fitting figure.figsize through rcParams before
    every run, and 8 of matplotlib's 29 styles set figure.figsize themselves --
    seaborn-v0_8, one of the curated style buttons, among them. mpl.style.use
    inside the block therefore used to throw the pane fit away on every re-run.
    The block now saves the host's keys, applies the style and puts them back,
    still before its own rcParams.update, so a key the student set beats both.

    The second half re-runs the block with the save/restore lines removed --
    exactly what the tool emitted before -- and asserts it DOES lose the value.
    Without that, a matplotlib release that stopped setting figure.figsize in
    seaborn-v0_8 would leave this test green and proving nothing.
    """
    source, expected = load("host_keys")
    host = {"figure.autolayout": True, "figure.figsize": [7.5, 5.0]}
    assert set(host) == set(expected["hostRcKeys"]), "fixture and sentinels disagree on the host's keys"

    mpl.rcParams.update(host)
    exec(compile(source, "host_keys.py", "exec"), {})
    assert list(mpl.rcParams["figure.figsize"]) == [7.5, 5.0]
    assert mpl.rcParams["figure.autolayout"] is True
    # ...and the style still did its job on everything else.
    assert mpl.rcParams["axes.facecolor"] == mpl.style.library[expected["style"]]["axes.facecolor"]

    mpl.rcdefaults()
    mpl.rcParams.update(host)
    exec(compile(strip_host_rc(source), "host_keys_stripped.py", "exec"), {})
    assert list(mpl.rcParams["figure.figsize"]) == list(
        mpl.style.library[expected["style"]]["figure.figsize"]
    ), "%s no longer clobbers figure.figsize; this fixture would prove nothing" % expected["style"]


def test_host_rc_preamble_binds_nothing_beyond_the_block():
    """The save/restore is three lines around style.use, and the name is deleted."""
    source, _ = load("host_keys")
    lines = source.splitlines()
    save = next(i for i, line in enumerate(lines) if line.startswith("%s = " % HOST_RC_VAR))
    use = next(i for i, line in enumerate(lines) if line.startswith("mpl.style.use("))
    restore = lines.index("mpl.rcParams.update(%s)" % HOST_RC_VAR)
    delete = lines.index("del %s" % HOST_RC_VAR)
    update = lines.index("mpl.rcParams.update({")
    assert save < use < restore < delete < update, (save, use, restore, delete, update)
    assert source.count(HOST_RC_VAR) == 3
    assert lines[save - 1] == HOST_RC_COMMENT

    namespace = {}
    exec(compile(source, "host_keys.py", "exec"), namespace)
    assert HOST_RC_VAR not in namespace


def test_host_rc_save_tolerates_a_key_this_matplotlib_does_not_have():
    """A host naming an rc key from another matplotlib version must not raise."""
    source, _ = load("host_keys")
    assert HOST_RC_VAR in source, "no save line left to tolerate anything"
    source = source.replace('"figure.autolayout"', '"figure.no.such.key"')
    assert "figure.no.such.key" not in mpl.rcParams
    exec(compile(source, "host_keys_unknown.py", "exec"), {})


def test_style_sheet_values_survive_under_overrides():
    source, _ = load("whitegrid")
    exec(source, {})
    assert mpl.rcParams["axes.grid"] is True
    assert mpl.rcParams["axes.edgecolor"] == ".8"  # from the whitegrid sheet, untouched by the block


# Values a host may have set before the block runs. Trinket sets
# figure.autolayout before every run, and figure.figsize in the worker; the rest
# are here so that ANY blanket reset -- mpl.rcdefaults(), mpl.style.use("default"),
# mpl.rcParams.update(mpl.rcParamsDefault) -- shows up as a diff whichever fixture
# is running. Pinning one key was not enough: `everything` sets figure.autolayout
# itself, so a block that wiped every host value and then re-set that one key
# passed. Every value here differs from the library default, which
# test_host_sentinels_differ_from_library_defaults keeps true.
HOST_RC = {
    "figure.autolayout": True,
    "figure.figsize": [7.5, 5.0],
    "figure.dpi": 111.0,
    "figure.facecolor": "#fedcba",
    "figure.edgecolor": "#abcdef",
    "figure.subplot.left": 0.2,
    "savefig.pad_inches": 0.42,
    "font.size": 11.5,
    "lines.linewidth": 3.25,
    "axes.grid": True,
    "axes.titlepad": 12.5,
    "xtick.major.pad": 7.5,
    "text.color": "#336699",
    "image.cmap": "plasma",
    "legend.borderpad": 0.55,
    "path.simplify": False,
}

# Reading these resolves a backend, which is a side effect, not a value to diff.
NOT_DIFFED = {"backend", "backend_fallback"}


def claimed_keys(expected):
    """Every rc key a block is entitled to change: its own, plus its style sheet's."""
    keys = set(expected["rc"])
    if expected["style"] != "default":
        keys |= set(mpl.style.library[expected["style"]])
    return keys


def rc_snapshot():
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return {key: repr(value) for key, value in mpl.rcParams.items() if key not in NOT_DIFFED}


def test_host_sentinels_differ_from_library_defaults():
    """A sentinel equal to the default would silently stop detecting a reset."""
    defaults = {key: repr(mpl.rcParams[key]) for key in HOST_RC}
    mpl.rcParams.update(HOST_RC)
    unchanged = sorted(key for key in HOST_RC if repr(mpl.rcParams[key]) == defaults[key])
    assert not unchanged, ("sentinels equal to the library default", unchanged)


@pytest.mark.parametrize("name", NAMES)
def test_block_leaves_host_rc_values_alone(name):
    """The block only ever ADDS its own settings; it never disturbs the rest of rc.

    Trinket sets figure.autolayout (and, in the worker, a pane-fitting
    figure.figsize) via rcParams before every run, and the block runs
    mid-program, so a reset inside the fence silently changes every figure the
    student draws. Checked by diffing rcParams across the exec rather than by
    grepping the source, so it is blind to spelling: rcdefaults(),
    style.use("default") and update(rcParamsDefault) all read the same. The
    second assertion catches the opposite failure -- a block that sets keys the
    settings never asked for, which nothing else here would notice.
    """
    source, expected = load(name)
    unknown = sorted(key for key in expected["rc"] if key not in mpl.rcParams)
    assert not unknown, ("fixture names rc keys this matplotlib does not have", unknown)

    claimed = claimed_keys(expected)
    host = {key: value for key, value in HOST_RC.items() if key not in claimed}
    assert len(host) >= 8, (name, "too few unclaimed sentinels left to detect a reset", sorted(host))

    mpl.rcParams.update(host)
    before = rc_snapshot()
    exec(compile(source, name + ".py", "exec"), {})
    after = rc_snapshot()

    clobbered = sorted(key for key in host if after[key] != before[key])
    assert not clobbered, ("%s: block reset host rc values it never set" % name, clobbered)
    stray = sorted(key for key in before if before[key] != after[key] and key not in claimed)
    assert not stray, (
        "%s: block changed rc keys that neither its own dict nor style %r claims" % (name, expected["style"]),
        stray,
    )
