/** The one place the tool's name appears in code. Renaming = editing this file. */
export const TOOL_NAME = "plotpolish";

export const VERSION = "0.3.1";

/** Custom element tag. */
export const ELEMENT_TAG = "plotpolish-panel";

/** Prefix for DOM events dispatched by the panel (`plotpolish-change`, …). */
export const EVENT_PREFIX = TOOL_NAME;

/** Fence markers. Matched at column 0 only; trailing whitespace tolerated. */
export const FENCE_START = `# --- plot style (generated by ${TOOL_NAME}; edit above, not here) ---`;
export const FENCE_END = "# --- end plot style ---";

/** Name of the variable the Python snippets leave their JSON result in. */
export const RESULT_VARIABLE = `__${TOOL_NAME}_result__`;

/**
 * Name the block binds while it carries the host's rc values across
 * `mpl.style.use`. It lives for three lines and is deleted; it is prefixed
 * with the tool name so it cannot plausibly collide with a student's global.
 */
export const HOST_RC_VARIABLE = `_${TOOL_NAME}_host_rc`;
