/** The one place the tool's name appears in code. Renaming = editing this file. */
export const TOOL_NAME = "plotpolish";

export const VERSION = "0.1.8";

/** Custom element tag. */
export const ELEMENT_TAG = "plotpolish-panel";

/** Prefix for DOM events dispatched by the panel (`plotpolish-change`, …). */
export const EVENT_PREFIX = TOOL_NAME;

/** Fence markers. Matched at column 0 only; trailing whitespace tolerated. */
export const FENCE_START = `# --- plot style (generated by ${TOOL_NAME}; edit above, not here) ---`;
export const FENCE_END = "# --- end plot style ---";

/** Name of the variable the Python snippets leave their JSON result in. */
export const RESULT_VARIABLE = `__${TOOL_NAME}_result__`;
